repos:
- repo: https://github.com/PyCQA/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [
            '--in-place',
            '--remove-unused-variables',
            '--remove-all-unused-imports',
            '--ignore-init-module-imports',
        ]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [
            '--line-length=240',
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      args: ['--line-length=240']

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--ignore=E129,E2,E722,E501,F541,F841,F405,F403,E712,W503']
